### ISSUE TITLE
N8N fails when Enterprise is in more than one group

### ISSUE THREAD

**Issue by kirstenalarsen** [openfoodfoundation/sib-discovery-components#62] opened 2024-05-15 23:24 UTC
@David-OFN-CA  @karlafalk please describe the problem

We think this problem is in the n8n workflow. @mkllnk to look at it first

If it is in the airtable, @amidaOFN or @karlafalk to work it out

**Comment by mkllnk** [comment] 2024-05-23 04:56
@karlafalk Can you trigger this error and let me know? Then I can look at the failed execution in n8n and work with test data.

I have an idea where the problem is but I can't debug it without data.

**Comment by karlafalk** [comment] 2024-05-23 10:02
@mkllnk Yes!  I did it just now and the 'failed' execution in visible under Executions from May 23rd and labelled [AUS Discover Regen workflow_Karla working](https://n8n.openfoodnetwork.org/executions#)

Thank you!

**Comment by mkllnk** [comment] 2024-05-23 23:06
Thank you! I can see the failed workflow and I know why it's failing. I can't reproduce it though because the enterprise now exists and I don't have access to delete it. It looks like the workflow to delete enterprises is missing. I added it to the forum:

* https://community.openfoodnetwork.org/t/n8n-workflows-for-the-discover-regenerative-api/2954/7

Can you import that one? I'm asking you to do it so that the permissions are set correctly in n8n.

**Comment by mkllnk** [comment] 2024-05-23 23:24
I think I fixed the workflow but I couldn't re-produce it. So please test.

**Comment by karlafalk** [comment] 2024-05-23 23:52
> Can you import that one? I'm asking you to do it so that the permissions are set correctly in n8n.

@mkllnk I imported that workflow, but not sure I understand how it is triggered.  I had to change the webhook url, because 'https://n8n.openfoodnetwork.org/webhook-test/remove-enterprise' was already taken, so I changed it to 'https://n8n.openfoodnetwork.org/webhook-test/remove-enterprise_CAN', but does this have to correspond with a translation for the connected apps button 'Stop Sharing'?

**Comment by karlafalk** [comment] 2024-05-24 00:02
> I think I fixed the workflow but I couldn't re-produce it. So please test.

@mkllnk I retested the workflow and now it is adding the Waterloo Enterprise (belonging to groups Buy Waterloo and Volunteer Waterloo) to the Airtable database.  Workflow executed successfully. However, only one Assurance/Group is appearing in the Airtable table.  

<img width="1488" alt="Screenshot 2024-05-23 at 7 49 34 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/13632890-5c1b-4df0-8696-fa09c9d4b78a">

<img width="947" alt="Screenshot 2024-05-23 at 8 00 15 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/5b171215-b7ae-4029-92d1-6c0100b8956e">

**Comment by mkllnk** [comment] 2024-05-24 02:13
The workflow that creates an enterprise returns the URL to the workflow to remove the enterprise. I'll update it.

**Comment by mkllnk** [comment] 2024-05-24 02:16
I renamed the webhook to `https://n8n.openfoodnetwork.org/webhook/regen_CAN/remove-enterprise`. I updated that in both Respond to Webhook nodes of the creation workflow.

**Comment by mkllnk** [comment] 2024-05-24 02:29
Regarding only one group being set, I don't know why. I replaced the Airtable node looking up the group. Maybe that will help? Try again.

**Comment by karlafalk** [comment] 2024-05-24 17:56
I just reran things and the workflow succeeded, but it is still not adding more than one assurance/group to the airtable base. But this time it add Group #66 (Volunteer Waterloo) instead of #65 (Buy Waterloo). 
<img width="1193" alt="Screenshot 2024-05-24 at 1 52 37 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/1bf581df-497c-4547-ad68-1f8f8166625c">

**Comment by karlafalk** [comment] 2024-05-27 13:08
@mkllnk For some reason the 'Executions' history disapeared in n8n, so I re-ran things again today.  This time only 'Buy Waterloo' was posted to the Assurance table in Airtable.
<img width="1586" alt="Screenshot 2024-05-27 at 9 03 57 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/75da29ad-1ce8-4e6e-b3ba-a67d58bcc6c3">

I noticed in the Airtable workflow the node, 'split out' before the Create Assurance section shows two items (for the 2 groups).
<img width="1872" alt="Screenshot 2024-05-27 at 9 00 33 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/1a4c482b-7d0d-42aa-b923-5197c10f737d">

But then the next node, 'Find Group' in Airtable has only 1 output item (1 group).  It seems to me like there should be an output item for each group here?  
<img width="1881" alt="Screenshot 2024-05-27 at 9 01 33 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/35124367-f5f5-4f4b-abfe-47b1f4b10c3e">

**Comment by mkllnk** [comment] 2024-05-28 01:16
Yes, exactly. I saw that, too. I thought that Airtable would run the search for each item. But maybe it runs only once for all inputs and we need to query a list. That is more efficient anyway. I just need to figure out the filter condition code.

**Comment by mkllnk** [comment] 2024-05-28 01:53
I found help in the community forum:

* https://community.n8n.io/t/more-items-passing-through-two-airtable-listed-nodes-but-only-one-item-in-the-final-output/23033

I set it up to loop through the groups. That seems to be a limitation of Airtable.

I also tried to query all groups at once to avoid the loop but Airtable doesn't seem to support this kind of filter:

* https://community.airtable.com/t5/development-apis/how-to-query-multiple-records/td-p/118336

**Comment by karlafalk** [comment] 2024-05-29 10:36
Thanks @mkllnk!  I tested things again (removing records from Airtable first) and now the workflow doesn't seem to be picking up either of the groups, and no 'assurances' are getting posted to airtable.  It looks like the issues starts at the 'DFC data after enterprise creation' node where there is no output data, and the dfc-b:affiliates don't seem to come through?  

<img width="2178" alt="Screenshot 2024-05-29 at 6 29 29 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/9201dadd-17d7-42e1-8a5c-dd4e66792c4f">

**Comment by mkllnk** [comment] 2024-05-29 23:01
Hm, there was a missing connection to the input of that node. Maybe I accidentally removed it. I put it back now.

**Comment by karlafalk** [comment] 2024-05-30 00:33
Thanks!  That fixed the 'DFC data after enterprise creation' node and the dfc-b:affiliates are back, but now things seem to get stuck at 'Split Out' with no output data.
<img width="2223" alt="Screenshot 2024-05-29 at 8 29 33 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/b722ec92-dfaa-46db-8a56-a6998a316eb8">

**Comment by mkllnk** [comment] 2024-05-31 03:08
Ah, I see. I connected from the wrong node. Please try again. :crossed_fingers:

**Comment by karlafalk** [comment] 2024-06-03 16:41
@mkllnk Sorry I had tested this last week and written a response, but it looks like maybe I didn't send before closing the page or something as it is not here now!

Anyways, it is working now and bringing in the assurances if a enterprise is in more than one group!  Yay! The only issue remaining with this is that the Assured Enterprise Field in the Airtable Assurances table is not getting auto-populated when the assurances are added (I have to manually add them).  

<img width="1214" alt="Screenshot 2024-05-31 at 9 41 42 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/4e429430-18da-449b-9a81-5a3867b83e5c">

I think this field is supposed to be posted with the rest of the data.  When I look at the airtable node for 'Create Assurance' the field 'Assured Enterprise' is included.  

<img width="2092" alt="Screenshot 2024-06-03 at 12 34 26 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/290b2d56-42df-4d01-988e-7798b29c1b53">

The problem seems to be in the node 'Set assurance fields' where the code for this field is in red.  

<img width="2196" alt="Screenshot 2024-05-31 at 9 38 40 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/69d0bb69-0232-413a-afbe-3f9d72779d5d">

I am wondering if we can make this code go green, then the Assured Enterprise field would be auto-populated in Airtable?

I thought maybe it also had something to do with 'Add Enterprise Record ID' like for the Products table (as the incoming products automatically get linked to the Enterprise record), but wasn't sure the correct place to insert that node or if this would work??

<img width="788" alt="Screenshot 2024-05-31 at 9 37 05 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/aa949b59-f733-4e0f-b7ff-31bed883af26">

**Comment by mkllnk** [comment] 2024-06-04 05:13
You are right, the node fails to read the attribute from the Create enterprise node. I added a couple more nodes to bring the information into the loop but I don't know if it will work. Can you try?

**Comment by karlafalk** [comment] 2024-06-04 14:02
@mkllnk That worked and now the Enterprise name is getting auto-populated to the field 'Assured enterprise', but I think it has interfered with the looping, as now only one assurance came through.  
<img width="802" alt="Screenshot 2024-06-04 at 9 55 02 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/1d963bd0-7cab-49a1-96bc-ab0fa86046fe">

You can see that the last node 'Create assurance' only has one output item, and only input run 1 of 2 has data (Run 2 of 2 has no data)?

<img width="1853" alt="Screenshot 2024-06-04 at 9 56 40 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/81d2d849-d06c-4ba4-83de-7ebcda7e7ae8">

Wondering if the 'Set assured enterprise id' node needs to be added in before the loop?

**Comment by karlafalk** [comment] 2024-06-04 14:09
On a related note, I noticed that the Delete Enterprise workflow is only working successfully sometimes.  Looking more closely I think this is because it is not working for enterprises that have no products.  The workflow gets stopped because it is still waiting for products to be deleted.  

<img width="1233" alt="Screenshot 2024-06-04 at 10 04 45 AM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/012ddefb-9708-485b-8e48-5649ec88c701">

Should another option/branch be added if no products are found, so the workflow can still proceed?

**Comment by mkllnk** [comment] 2024-06-05 02:09
Okay, merging data from outside a loop inside a loop didn't work as I hoped. So I now merge the data before the loop and everything we need to know goes in the loop together. I hope that works.

**Comment by mkllnk** [comment] 2024-06-05 02:19
> Delete Enterprise workflow

I switched the nodes around product deletion to always output data and I inserted an IF statement so that the deletion doesn't fail if there is no product. Hopefully that works. :crossed_fingers:

**Comment by karlafalk** [comment] 2024-06-05 19:53
> Okay, merging data from outside a loop inside a loop didn't work as I hoped. So I now merge the data before the loop and everything we need to know goes in the loop together. I hope that works.

Beautiful! @mkllnk This works now as expected.

**Comment by karlafalk** [comment] 2024-06-05 20:04
> I switched the nodes around product deletion to always output data and I inserted an IF statement so that the deletion doesn't fail if there is no product. Hopefully that works. 🤞

@mkllnk This is working OK now. The enterprise is getting deleted, however the Assurance is not getting fully deleted only parts, which look like it is linked to the 'Delete Assurance' node.

<img width="1667" alt="Screenshot 2024-06-05 at 3 48 38 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/1f0be993-72a2-46fb-ae68-940f4bb4be81">

The data in the fields 'Assured enterprise' and 'Assured enterprise RecordID' gets removed with the delete, but the assurance records themselves in the Assurance table still remain.

<img width="785" alt="Screenshot 2024-06-05 at 3 49 33 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/37ddee26-2ffd-4d85-8ebf-f7ebf23f7be6">

<img width="921" alt="Screenshot 2024-06-05 at 3 49 42 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/a301af3d-8852-437b-8057-feaedebcc995">

<img width="934" alt="Screenshot 2024-06-05 at 4 01 24 PM" src="https://github.com/openfoodfoundation/sib-discovery-components/assets/88801240/98826a49-6520-484e-8f5f-e626e7abb726">

I don't think this is a really important for our project as effectively the enterprise will still get removed from the directory, but I am just noting it here that the workflow is not working as fully expected.

**Comment by mkllnk** [comment] 2024-06-05 22:03
> The data in the fields 'Assured enterprise' and 'Assured enterprise RecordID' gets removed with the delete, but the assurance records themselves in the Assurance table still remain.

That was intentional in our project. People can add more data manually to their assurance data and we didn't want to delete the manually entered data. So if people disconnected the app in OFN and then re-connected, there data isn't lost. It could probably be implemented better but we didn't see a need for that at this stage.

**Comment by mkllnk** [comment] 2024-06-05 22:04
Can we close this issue, @karlafalk?

**Comment by karlafalk** [comment] 2024-06-05 22:56
> Can we close this issue, @karlafalk?

Yup, I think we are good to close this issue @David-OFN-CA @mkllnk Thanks!

**Closed as completed** 2024-06-06 00:13 UTC
